language: ruby
rvm:
  - 1.9.3
env:
  secure: "D/xOWVqYcxmZyR18Sj93VcW9LaoPZcRN5aSzDCAcODtyFjRfihIxe6/G41do\nxf1lhU4aUm7d2ht7Vwh4TIPc+euTeGM2DRZviOqYMdEnhoxZd4B1TBjyzwkK\ntZWBFSBOetw0ocmFBlSo1iAKWm7oQQo1qAV5fs2W7Da5Y+lzbgU="
before_script:
  - "rake db:migrate RAILS_ENV=test"

after_script:
  - gem install heroku
  - yes | ruby travis_deployer.rb
  - heroku keys:clear
  - yes | heroku keys:add
  - git push heroku master

notifications:
  email:
    recipients:
      - paulswilliams@me.com 
      - rob.porter.work@gmail.com
      - william.olner@gmail.com
      - jay.underhill@gmail.com
    #on_success: always # default: change
    on_failure: always # default: always
    # on_failure: [always|never|change] # default: always
