language: ruby
rvm:
  - 1.9.3
env:
  secure: "HURu6FJwYgDeHNkQebUmhc/km39ENCmqjdV/J69fnfCCUwrCFxQ1iMqgoq4t\nwBZoZLerLoV1YlicUSWSxd9SFLkhuHPoihGcU1n7S3JtddVhRG57m8Dk1oUt\n+QkAwgOA0ZrMRbR6e1/l+QNT3V15/rfueExH4nzqiZDrIw+MaKY="
before_script:
  - "rake db:migrate RAILS_ENV=test"

after_script:
  - gem install heroku
  - yes | ruby travis_deployer.rb
  - heroku keys:clear
  - yes | heroku keys:add
  - git push heroku master

notifications:
  email:
    recipients:
      - paulswilliams@me.com 
      - rob.porter.work@gmail.com
      - william.olner@gmail.com
      - jay.underhill@gmail.com
    #on_success: always # default: change
    on_failure: always # default: always
    # on_failure: [always|never|change] # default: always
